spring.application.name=web-api-blogging
# SERVER CONFIG
server.port=3001
# DB CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/api-blogging
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=update